// Generates globals.css and the shadcn registry items in public/r/ from tokens.json,
// after checking WCAG contrast in both modes. Run: node build.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"

process.chdir(new URL(".", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1"))
const t = JSON.parse(readFileSync("tokens.json", "utf8"))

// --- Contrast check: fails the build if any pair drops below its minimum ---
const HEX = /^#[0-9a-f]{6}$/i
for (const mode of ["light", "dark"]) {
  for (const [k, v] of Object.entries(t[mode])) {
    if (!HEX.test(v)) throw new Error(`${mode}.${k} must be #RRGGBB (got "${v}") so contrast can be checked`)
  }
}
const rgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16))
const lum = (hex) => {
  const c = rgb(hex).map((v) => v / 255)
    .map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4))
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]
}
const ratio = (a, b) => {
  const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p)
  return (x + 0.05) / (y + 0.05)
}
// colour `a` at `alpha` over `b`, e.g. shadcn's dark:bg-destructive/60
const over = (a, alpha, b) =>
  "#" + rgb(a).map((v, i) => Math.round(v * alpha + rgb(b)[i] * (1 - alpha)).toString(16).padStart(2, "0")).join("")

const PAIRS = [
  ["foreground", "background", 4.5], ["card-foreground", "card", 4.5],
  ["popover-foreground", "popover", 4.5], ["primary-foreground", "primary", 4.5],
  ["secondary-foreground", "secondary", 4.5], ["accent-foreground", "accent", 4.5],
  ["accent-foreground", "popover", 4.5],
  ["muted-foreground", "background", 4.5], ["muted-foreground", "muted", 4.5],
  ["muted-foreground", "secondary", 4.5], ["muted-foreground", "card", 4.5],
  ["primary", "background", 4.5], ["primary", "card", 4.5],
  ["destructive", "background", 4.5], ["destructive", "card", 4.5],
  ["success", "background", 4.5], ["success", "card", 4.5],
  ["sidebar-foreground", "sidebar", 4.5], ["sidebar-primary-foreground", "sidebar-primary", 4.5],
  ["sidebar-accent-foreground", "sidebar-accent", 4.5],
  ["input", "background", 3], ["ring", "background", 3],
  ...[1, 2, 3, 4, 5].map((n) => [`chart-${n}`, "background", 3]),
]
const failures = []
const check = (label, fg, bg, min) => {
  const r = ratio(fg, bg)
  if (r < min) failures.push(`${label} = ${r.toFixed(2)} (< ${min})`)
}
for (const mode of ["light", "dark"]) {
  for (const [fg, bg, min] of PAIRS) check(`${mode}: ${fg} on ${bg}`, t[mode][fg], t[mode][bg], min)
}
// shadcn's destructive button: white text on bg-destructive (light) / bg-destructive/60 (dark)
check("light: white on destructive button", "#FFFFFF", t.light.destructive, 4.5)
check("dark: white on destructive button", "#FFFFFF", over(t.dark.destructive, 0.6, t.dark.background), 4.5)
if (failures.length) {
  console.error("Contrast check failed:\n  " + failures.join("\n  "))
  process.exit(1)
}

// --- Shared pieces ---
const themeVars = { "font-sans": t.font.sans }
for (const [name, s] of Object.entries(t.text)) {
  themeVars[`text-${name}`] = s.size
  for (const k of ["line-height", "font-weight", "letter-spacing"]) {
    if (s[k]) themeVars[`text-${name}--${k}`] = s[k]
  }
}
// ponytail: 44px targets via min-height on touch screens instead of forking shadcn components;
// relies on shadcn's data-slot attributes. Fork button/input only if a framework drops them.
const touchSelectors = '[data-slot="button"], [data-slot="input"], [data-slot="select-trigger"], [data-slot="tabs-trigger"]'
const css = {
  "@layer base": {
    "html": { "color-scheme": "light" },
    "html.dark": { "color-scheme": "dark" },
    "@media (pointer: coarse)": {
      [touchSelectors]: { "min-height": "2.75rem" },
      // newer shadcn buttons drop data-size, so icon buttons can't be targeted; text buttons exceed 44px anyway
      '[data-slot="button"]': { "min-width": "2.75rem" },
    },
    "@media (prefers-reduced-motion: reduce)": {
      "*, *::before, *::after": {
        "animation-duration": "0.01ms !important",
        "transition-duration": "0.01ms !important",
      },
    },
  },
}

// --- globals.css (for copying by hand) ---
const block = (vars, indent = "  ") =>
  Object.entries(vars).map(([k, v]) => `${indent}--${k}: ${v};`).join("\n")
const cssText = (obj, indent = "") =>
  Object.entries(obj).map(([sel, body]) =>
    typeof body === "string"
      ? `${indent}${sel}: ${body};`
      : `${indent}${sel} {\n${cssText(body, indent + "  ")}\n${indent}}`
  ).join("\n")
const colorNames = Object.keys(t.light)
writeFileSync("globals.css", `/* GENERATED by build.mjs from tokens.json — edit tokens.json, not this file. */
@import "tailwindcss";
@import "tw-animate-css";

@custom-variant dark (&:is(.dark *));

:root {
  --radius: ${t.radius};
${block(t.light)}
}

.dark {
${block(t.dark)}
}

@theme inline {
${block(themeVars)}
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
${colorNames.map((n) => `  --color-${n}: var(--${n});`).join("\n")}
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground font-sans antialiased;
  }
}

${cssText(css)}
`)

// --- Registry items (one JSON per item, installable by URL) ---
mkdirSync("public/r", { recursive: true })
const file = (path, type, target) => ({
  path, type, ...(target && { target }), content: readFileSync(path, "utf8"),
})
const items = [
  {
    name: "graphite",
    type: "registry:theme",
    title: "Graphite theme",
    description: "Graphite colours, type and radius for light and dark mode, plus 44px touch targets.",
    cssVars: { theme: themeVars, light: { radius: t.radius, ...t.light }, dark: t.dark },
    css,
  },
  {
    name: "graphite-next-dark-mode",
    type: "registry:component",
    title: "Graphite dark mode (Next.js)",
    description: "next-themes provider and a light/dark toggle button.",
    dependencies: ["next-themes", "lucide-react"],
    registryDependencies: ["button"],
    files: [
      file("registry/next/theme-provider.tsx", "registry:component"),
      file("registry/next/mode-toggle.tsx", "registry:component"),
    ],
  },
  {
    name: "graphite-svelte-dark-mode",
    type: "registry:component",
    title: "Graphite dark mode (SvelteKit)",
    description: "mode-watcher based light/dark toggle button.",
    dependencies: ["mode-watcher", "@lucide/svelte"],
    registryDependencies: ["button"],
    files: [file("registry/svelte/mode-toggle.svelte", "registry:component", "mode-toggle.svelte")],
  },
]
for (const item of items) {
  writeFileSync(`public/r/${item.name}.json`, JSON.stringify(
    { $schema: "https://ui.shadcn.com/schema/registry-item.json", ...item }, null, 2) + "\n")
}
console.log(`ok: contrast passed, wrote globals.css and ${items.length} registry items`)
