// Generates globals.css and the shadcn registry items in public/r/ from tokens.json,
// after checking WCAG contrast in both modes. Run: node build.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname } from "node:path"
import { fileURLToPath } from "node:url"

process.chdir(dirname(fileURLToPath(import.meta.url)))
const t = JSON.parse(readFileSync("tokens.json", "utf8"))

// --- Contrast check: fails the build if any pair drops below its minimum ---
const HEX = /^#[0-9a-f]{6}$/i
for (const mode of ["light", "dark"]) {
  for (const [k, v] of Object.entries(t[mode])) {
    if (!HEX.test(v)) throw new Error(`${mode}.${k} must be #RRGGBB (got "${v}") so contrast can be checked`)
  }
}
const rgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16))
const lum = (hex) => {
  const c = rgb(hex).map((v) => v / 255)
    .map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4))
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]
}
const ratio = (a, b) => {
  const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p)
  return (x + 0.05) / (y + 0.05)
}
// colour `a` at `alpha` over `b`, e.g. shadcn's dark:bg-destructive/60
const over = (a, alpha, b) =>
  "#" + rgb(a).map((v, i) => Math.round(v * alpha + rgb(b)[i] * (1 - alpha)).toString(16).padStart(2, "0")).join("")

const PAIRS = [
  ["foreground", "background", 4.5], ["card-foreground", "card", 4.5],
  ["popover-foreground", "popover", 4.5], ["primary-foreground", "primary", 4.5],
  ["secondary-foreground", "secondary", 4.5], ["accent-foreground", "accent", 4.5],
  ["accent-foreground", "popover", 4.5],
  ["muted-foreground", "background", 4.5], ["muted-foreground", "muted", 4.5],
  ["muted-foreground", "secondary", 4.5], ["muted-foreground", "card", 4.5],
  ["primary", "background", 4.5], ["primary", "card", 4.5],
  ["destructive", "background", 4.5], ["destructive", "card", 4.5],
  ["success", "background", 4.5], ["success", "card", 4.5],
  ["sidebar-foreground", "sidebar", 4.5], ["sidebar-primary-foreground", "sidebar-primary", 4.5],
  ["sidebar-accent-foreground", "sidebar-accent", 4.5],
  ["input", "background", 3], ["ring", "background", 3],
  ...[1, 2, 3, 4, 5].map((n) => [`chart-${n}`, "background", 3]),
]
const failures = []
const check = (label, fg, bg, min) => {
  const r = ratio(fg, bg)
  if (r < min) failures.push(`${label} = ${r.toFixed(2)} (< ${min})`)
}
for (const mode of ["light", "dark"]) {
  for (const [fg, bg, min] of PAIRS) check(`${mode}: ${fg} on ${bg}`, t[mode][fg], t[mode][bg], min)
}
// shadcn's destructive button: white text on bg-destructive (light) / bg-destructive/60 (dark)
check("light: white on destructive button", "#FFFFFF", t.light.destructive, 4.5)
check("dark: white on destructive button", "#FFFFFF", over(t.dark.destructive, 0.6, t.dark.background), 4.5)
if (failures.length) {
  console.error("Contrast check failed:\n  " + failures.join("\n  "))
  process.exit(1)
}

// --- Shared pieces ---
const themeVars = { "font-sans": t.font.sans }
for (const [name, s] of Object.entries(t.text)) {
  themeVars[`text-${name}`] = s.size
  for (const k of ["line-height", "font-weight", "letter-spacing"]) {
    if (s[k]) themeVars[`text-${name}--${k}`] = s[k]
  }
}
// ponytail: 44px targets via min-height on touch screens instead of forking shadcn components;
// relies on shadcn's data-slot attributes. Fork button/input only if a framework drops them.
const touchSelectors = '[data-slot="button"], [data-slot="input"], [data-slot="select-trigger"], [data-slot="tabs-trigger"]'
const css = {
  "@layer base": {
    "html": { "color-scheme": "light" },
    "html.dark": { "color-scheme": "dark" },
    "@media (pointer: coarse)": {
      [touchSelectors]: { "min-height": "2.75rem" },
      // newer shadcn buttons drop data-size, so icon buttons can't be targeted; text buttons exceed 44px anyway
      '[data-slot="button"]': { "min-width": "2.75rem" },
    },
    "@media (prefers-reduced-motion: reduce)": {
      "*, *::before, *::after": {
        "animation-duration": "0.01ms !important",
        "transition-duration": "0.01ms !important",
      },
    },
  },
}

// --- globals.css (for copying by hand) ---
const block = (vars, indent = "  ") =>
  Object.entries(vars).map(([k, v]) => `${indent}--${k}: ${v};`).join("\n")
const cssText = (obj, indent = "") =>
  Object.entries(obj).map(([sel, body]) =>
    typeof body === "string"
      ? `${indent}${sel}: ${body};`
      : `${indent}${sel} {\n${cssText(body, indent + "  ")}\n${indent}}`
  ).join("\n")
const colorNames = Object.keys(t.light)
writeFileSync("globals.css", `/* GENERATED by build.mjs from tokens.json — edit tokens.json, not this file. */
@import "tailwindcss";
@import "tw-animate-css";

@custom-variant dark (&:is(.dark *));

:root {
  --radius: ${t.radius};
${block(t.light)}
}

.dark {
${block(t.dark)}
}

@theme inline {
${block(themeVars)}
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
${colorNames.map((n) => `  --color-${n}: var(--${n});`).join("\n")}
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground font-sans antialiased;
  }
}

${cssText(css)}
`)

// --- Registry items (one JSON per item, installable by URL) ---
mkdirSync("public/r", { recursive: true })
const file = (path, type, target) => ({
  path, type, ...(target && { target }), content: readFileSync(path, "utf8"),
})
const items = [
  {
    name: "graphite",
    type: "registry:theme",
    title: "Graphite theme",
    description: "Graphite colours, type and radius for light and dark mode, plus 44px touch targets.",
    cssVars: { theme: themeVars, light: { radius: t.radius, ...t.light }, dark: t.dark },
    css,
  },
  {
    name: "graphite-next-dark-mode",
    type: "registry:component",
    title: "Graphite dark mode (Next.js)",
    description: "next-themes provider and a light/dark toggle button.",
    dependencies: ["next-themes", "lucide-react"],
    registryDependencies: ["button"],
    files: [
      file("registry/next/theme-provider.tsx", "registry:component"),
      file("registry/next/mode-toggle.tsx", "registry:component"),
    ],
  },
  {
    name: "graphite-svelte-dark-mode",
    type: "registry:component",
    title: "Graphite dark mode (SvelteKit)",
    description: "mode-watcher based light/dark toggle button.",
    dependencies: ["mode-watcher", "@lucide/svelte"],
    registryDependencies: ["button"],
    files: [file("registry/svelte/mode-toggle.svelte", "registry:component", "mode-toggle.svelte")],
  },
]
for (const item of items) {
  writeFileSync(`public/r/${item.name}.json`, JSON.stringify(
    { $schema: "https://ui.shadcn.com/schema/registry-item.json", ...item }, null, 2) + "\n")
}
console.log(`ok: contrast passed, wrote globals.css and ${items.length} registry items`)

// --- Claude Design system tokens (claude-design/tokens.json, the Design System artifact's format) ---
const usage = {
  background: "Page background. App default theme is dark.",
  foreground: "Primary text on background.",
  card: "Cards, sheets and the sidebar surface; one step off the background.",
  "card-foreground": "Text on card.",
  popover: "Menus, popovers, dialogs.",
  "popover-foreground": "Text on popover.",
  primary: "The accent: the ONE primary action per screen, selected state, links, progress. Never decoration.",
  "primary-foreground": "Text and icons on primary fills.",
  secondary: "Secondary buttons, tab-list track, filled chips.",
  "secondary-foreground": "Text on secondary.",
  muted: "Quiet fills: skeletons, disabled areas.",
  "muted-foreground": "Captions, helper text, inactive tabs, metadata. Passes 4.5:1 on background, card and secondary.",
  accent: "Hover/active fill for ghost and outline controls and menu items (shadcn's accent, not the brand accent).",
  "accent-foreground": "Text on accent.",
  destructive: "Errors and destructive actions. As text, or as a button fill with white text (dark mode dims it to 60%).",
  success: "Confirmation and positive status. Pair with an icon or text.",
  border: "Card outlines and dividers. Decorative.",
  input: "Input, select and outline-button borders; 3:1 against background.",
  ring: "Focus ring, shown on :focus-visible only.",
  sidebar: "Sidebar surface.",
  "sidebar-foreground": "Text in the sidebar.",
  "sidebar-primary": "Active sidebar item fill.",
  "sidebar-primary-foreground": "Text on the active sidebar item.",
  "sidebar-accent": "Sidebar hover fill.",
  "sidebar-accent-foreground": "Text on sidebar hover.",
  "sidebar-border": "Sidebar divider.",
  "sidebar-ring": "Sidebar focus ring.",
}
for (let n = 1; n <= 5; n++) usage[`chart-${n}`] = `Chart series ${n}; 3:1 against background.`
const missing = colorNames.filter((n) => !usage[n])
if (missing.length) throw new Error(`add a usage note in build.mjs for: ${missing.join(", ")}`)

const style = (name, s, fontWeight, sample, note) => ({
  name, fontSize: `${parseFloat(s.size) * 16}px`, lineHeight: `${parseFloat(s["line-height"]) * 16}px`,
  fontWeight, ...(s["letter-spacing"] && { letterSpacing: s["letter-spacing"] }), sample, usage: note,
})
const dsTokens = {
  name: "Graphite", version: 1,
  meta: { source: { kind: "code", repo: "https://github.com/mastalier1997/design-system", file: "tokens.json" } },
  color: {
    themes: [{ id: "light", name: "Light" }, { id: "dark", name: "Dark" }],
    tokens: colorNames.map((name) => ({ name, value: { light: t.light[name], dark: t.dark[name] }, usage: usage[name] })),
  },
  type: {
    fonts: [],
    families: { sans: t.font.sans },
    groups: [
      { name: "Headings", family: "sans", styles: [
        style("display", t.text.display, 700, "Choose your split", "Screen title, one per screen (Tailwind: text-display)."),
        style("h2", t.text.h2, 600, "Push day · 5 exercises", "Section headers, card titles that lead (text-h2)."),
      ] },
      { name: "Text", family: "sans", styles: [
        style("body", t.text.body, 400, "Body text for inputs and descriptions.", "Default copy and input text (text-body). Inputs stay 16px so iOS doesn't zoom."),
        style("body-medium", t.text.body, 500, "Romanian deadlift", "Card titles, list item names."),
        { name: "ui", fontSize: "14px", lineHeight: "20px", fontWeight: 500, sample: "Start workout", usage: "Button and tab labels: shadcn's text-sm font-medium." },
        style("label", t.text.label, 600, "HAMSTRINGS", "Tags and small labels, always uppercase (text-label uppercase)."),
        style("caption", t.text.caption, 400, "Last time 60 kg", "Captions, helper text, metadata. 13px is the floor for any UI text."),
      ] },
    ],
  },
  spacing: { tokens: [
    ["space-1", "4px", "Icon-to-label gaps inside small controls."], ["space-2", "8px", "Gap between chips, inline items."],
    ["space-3", "12px", "Gap between stacked cards."], ["space-4", "16px", "Screen side padding on phones; card padding."],
    ["space-6", "24px", "Card padding (roomy); screen padding from sm up."], ["space-8", "32px", "Space between major sections."],
    ["space-12", "48px", "Large section breaks."], ["space-16", "64px", "Page-level top/bottom space."],
  ].map(([name, value, u]) => ({ name, value, usage: `${u} Tailwind's 4px scale.` })) },
  radius: { tokens: [
    { name: "radius-sm", value: "6px", usage: "Badges, checkboxes (rounded-sm)." },
    { name: "radius-md", value: "8px", usage: "Buttons, inputs, tags (rounded-md)." },
    { name: "radius-lg", value: `${parseFloat(t.radius) * 16}px`, usage: "Base --radius: tab lists, alerts (rounded-lg)." },
    { name: "radius-xl", value: "14px", usage: "Cards, sheets, dialogs (rounded-xl)." },
    { name: "radius-full", value: "9999px", usage: "Pills, switches, progress bars, avatars." },
  ] },
  size: { tokens: [
    { name: "control-touch", value: "44px", usage: "Minimum height (and width) of buttons, inputs, selects and tab triggers on touch screens." },
    { name: "content-max", value: "448px", usage: "Max width of the single app column (max-w-md)." },
  ] },
}
writeFileSync("claude-design/tokens.json", JSON.stringify(dsTokens, null, 2) + "\n")
console.log("ok: wrote claude-design/tokens.json")
